FROM gitpod/workspace-full-vnc
LABEL org.opencontainers.image.source = "https://github.com/W3Dev/gitpod-workspaces"

RUN sudo apt update -y
RUN sudo add-apt-repository ppa:maarten-fonville/android-studio
RUN sudo apt update -y
RUN sudo apt install android-studio -y

