FROM gitpod/workspace-full-vnc

ENV container docker
ENV PATH /snap/bin:$PATH
ADD snap /usr/local/bin/snap
RUN sudo apt-get update
RUN sudo apt-get install -y snapd squashfuse fuse
RUN sudo systemctl enable snapd
STOPSIGNAL SIGRTMIN+3
