FROM gitpod/workspace-full-vnc
LABEL org.opencontainers.image.source = "https://github.com/W3Dev/gitpod-workspaces"

USER gitpod

RUN npm install expo-cli --global

# TODO
# - [ ] Add Tailscale and Cloudflare Tunnel Support